### ISSUE TITLE
Error trying to stop the camera in ts

### ISSUE THREAD

**Issue by jecorrales-dev** [id1945/ngx-scanner-qrcode#1]
Hi, I've trying to stop the camera after I have the result of read the QR code but, I got this error:

```
     ERROR RangeError: Maximum call stack size exceeded
    at ErrorHandler._findOriginalError (core.mjs:7647:26)
    at ErrorHandler.handleError (core.mjs:7639:36)
    at handleError (core.mjs:13385:34)
    at executeListenerWithErrorHandling (core.mjs:15779:9)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core.mjs:15811:22)
    at Object.next (Subscriber.js:110:13)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at Subject.js:31:30
    at errorContext (errorContext.js:19:9)
```

I'm using the viewchild in this way, calling `this.action.stop(); ` or `this.action.toggleCamera();`

```
@ViewChild('action', { static: true })
  action!: NgxScannerQrcodeComponent;

  constructor() { }

  ngOnInit(): void {
  }

  public onError(e: any): void {
    console.log('event: ', e);
  }

  onRead(event: any) {
    this.output = event; //it works
    this.action.stop(); 
    this.action.toggleCamera();
  }

```

And if I try to stop the camera after scanned code I cant access to the value `output`. Can you help me please?

**Comment by faradoxuzb** [comment]
The same

**Comment by id1945** [comment]
I want you to recreate it on your stackblitz!  plz.

**Comment by jongbonga** [comment]
Same here

```
ERROR RangeError: Maximum call stack size exceeded
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:191:32)
    at SafeSubscriber.next (Subscriber.js:122:22)
    at Subscriber._next (Subscriber.js:72:26)
    at Subscriber.next (Subscriber.js:49:18)
    at EventEmitter_.next (Subject.js:39:25)
    at EventEmitter_.emit (core.mjs:22886:15)
    at NgxScannerQrcodeComponent.stop (ngx-scanner-qrcode.js:11036:19)
    at WebScannerPage.dismiss (web-scanner.page.ts:27:17)
    at WebScannerPage_Template_ngx_scanner_qrcode_data_11_listener (template.html:16:11)
    at executeListenerWithErrorHandling (core.mjs:15778:16)
```

**Comment by id1945** [comment]
> Same here
> 
> ```
> ERROR RangeError: Maximum call stack size exceeded
>     at SafeSubscriber.__tryOrUnsub (Subscriber.js:191:32)
>     at SafeSubscriber.next (Subscriber.js:122:22)
>     at Subscriber._next (Subscriber.js:72:26)
>     at Subscriber.next (Subscriber.js:49:18)
>     at EventEmitter_.next (Subject.js:39:25)
>     at EventEmitter_.emit (core.mjs:22886:15)
>     at NgxScannerQrcodeComponent.stop (ngx-scanner-qrcode.js:11036:19)
>     at WebScannerPage.dismiss (web-scanner.page.ts:27:17)
>     at WebScannerPage_Template_ngx_scanner_qrcode_data_11_listener (template.html:16:11)
>     at executeListenerWithErrorHandling (core.mjs:15778:16)
> ```

You can upgrate to v1.0.19

**Comment by jecorrales-dev** [comment]
I've solved this using this method, is it ok or can I use another best solution for this problem?

```
onRead(event: any) {
    const code = event;
    if (code != '' && code != null) {
      console.log('code: ', code);

      this.output = code;
      this.closeDialog();

      //Stop the camera service
      setInterval(() => {
        this.action.stop();
      }, 3000)
    }
  }
```

**Comment by id1945** [comment]
> I've solved this using this method, is it ok or can I use another best solution for this problem?
> 
> ```
> onRead(event: any) {
>     const code = event;
>     if (code != '' && code != null) {
>       console.log('code: ', code);
> 
>       this.output = code;
>       this.closeDialog();
> 
>       //Stop the camera service
>       setInterval(() => {
>         this.action.stop();
>       }, 3000)
>     }
>   }
> ```



> setInterval

I have updated to the new version and I think it will no longer have the above error. Can you try it and check if it still has the above error?

**Comment by jecorrales-dev** [comment]
It works! and congrats for the new version of this package!
