### ISSUE TITLE
ERROR Error: Uncaught (in promise): ReferenceError: zbarWasm is not defined

### ISSUE THREAD

**Issue by Nurech** [id1945/ngx-scanner-qrcode#12]
On `(click)="handle(action, 'start')"`. Using standard config.
```
scanner.component.ts:35 ERROR Error: Uncaught (in promise): ReferenceError: zbarWasm is not defined
ReferenceError: zbarWasm is not defined
    at NgxScannerQrcodeComponent.<anonymous> (ngx-scanner-qrcode.js:1081:26)
    at Generator.next (<anonymous>)
    at tslib.es6.js:74:1
    at new ZoneAwarePromise (zone.js:1429:21)
    at __awaiter (tslib.es6.js:70:1)
    at NgxScannerQrcodeComponent.drawImage (ngx-scanner-qrcode.js:1051:25)
```

`package.json`
```
"dependencies": {
    "@angular/animations": "^15.0.4",
    "@angular/cdk": "^15.0.4",
    "@angular/common": "^15.0.4",
    "@angular/compiler": "^15.0.4",
    "@angular/core": "^15.0.4",
    "@angular/fire": "^7.5.0",
    "@angular/forms": "^15.0.4",
    "@angular/material": "^15.0.0",
    "@angular/platform-browser": "^15.0.4",
    "@angular/platform-browser-dynamic": "^15.0.4",
    "@angular/router": "^15.0.4",
    "@angular/service-worker": "^15.0.4",
    "@ngrx/effects": "^15.1.0",
    "@ngrx/entity": "^15.1.0",
    "@ngrx/router-store": "^15.1.0",
    "@ngrx/schematics": "^15.1.0",
    "@ngrx/store": "^15.1.0",
    "@ngrx/store-devtools": "^15.1.0",
    "http-server": "^14.1.1",
    "ngrx-store-freeze": "^0.2.4",
    "ngrx-store-localstorage": "^15.0.0",
    "ngx-auto-unsubscribe": "^3.0.1",
    "ngx-scanner-qrcode": "^1.1.8",
    "primeflex": "^3.3.0",
    "primeicons": "^6.0.1",
    "primeng": "^15.0.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  }
```

**Comment by id1945** [comment]
It is recommended to declare it in the header of index.html
```html
<script src="https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.11/dist/index.js"></script>
```
