### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getUserMedia')

### ISSUE THREAD

**Issue by jonathanhendra** [id1945/ngx-scanner-qrcode#47]
im already try in localhost this library work but when i push to production i have error like this below

<img width="689" alt="image" src="https://github.com/id1945/ngx-scanner-qrcode/assets/17997094/1db673ff-2678-42bc-8269-f0535f64359e">

`ERROR TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at Object.next (788.313bfc184700d204.js:1:348579)
    at Fe.next (main.a08ea1e319e083a7.js:1:18459)
    at Ae._next (main.a08ea1e319e083a7.js:1:18126)
    at Ae.next (main.a08ea1e319e083a7.js:1:17809)
    at O._subscribe (main.a08ea1e319e083a7.js:1:13642)
    at O._trySubscribe (main.a08ea1e319e083a7.js:1:14418)
    at O._trySubscribe (main.a08ea1e319e083a7.js:1:16234)
    at main.a08ea1e319e083a7.js:1:14360
    at V (main.a08ea1e319e083a7.js:1:28385)
    at O.subscribe (main.a08ea1e319e083a7.js:1:14267)`

**Comment by daiduongdjv** [comment]
@jonathanhendra Looks like the error is the same as issue #25

**Comment by id1945** [comment]
@jonathanhendra Similar to issue #25
