### ISSUE TITLE
Angular 18 Internal server error: document is not defined

### ISSUE THREAD

**Issue by Dema-kun** [id1945/ngx-scanner-qrcode#79]
Good afternoon, I encountered the same problem. I registered the path to wasm in angular.json as stated in the README, I entered the npm start command, no errors appeared during the build. But after I go into the application, it gives an error
```
[vite] Internal server error: document is not defined
      at LOAD_WASM_RETRY (.\.angular\cache\18.2.12\project\vite\deps_ssr\ngx-scanner-qrcode.js:673:26)
      at Module.LOAD_WASM (.\.angular\cache\18.2.12\project\vite\deps_ssr\ngx-scanner-qrcode.js:719:3)
      at eval (.\src\app\pages\qr-code-info-page\qr-code-info-page.component.ts:12:1)
      at async instantiateModule (./node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:52914:5)
```
Just comment out the line: LOAD_WASM('assets/wasm/ngx-scanner-qrcode.wasm').subscribe(); everything starts to work fine, but in the absence of the Internet the code cannot be read, and you need to work offline. 
Maybe someone has encountered such a problem and knows how to solve it?

**Comment by jssmotta** [comment]
I added "/" LOAD_WASM('/assets/wasm/ngx-scanner-qrcode.wasm').subscribe(); and started it an ngOnInit.
